### ISSUE TITLE
Proxy feature

### ISSUE THREAD

**Issue by Tux-Panik** [jonathan6661/Inoitsu-analyzer#1]
Hi Jonathan,

Sounds interesting and accurate.
Are you considering adding an appropriate feature to manage HTTP proxies?

Thanks.
Kind regards,
Julien

**Comment by jonathan6661** [comment]
Hi @Tux-Panik,

Thank you for reaching out.
You want to make requests using different HTTP proxies to avoid blockage ?
If yes, this will be added sooner.

Regards,
jhon.

**Comment by Tux-Panik** [comment]
Hi there, 
> You want to make requests using different HTTP proxies to avoid blockage ?

Not really. It's mostly a proxy capability for Cortex instances hosted in an enterprise environment. 
Users must set their Corporate proxy settings to allow the analyzer to connect the destination through the proxy. 

Most of analyzers have this capability. 
I hope it helps. 
Thanks. Julien.

**Comment by jonathan6661** [comment]
Hi Julien,
Understood, this will be added right away.
Thank you for your recommendation.
Jhon :)

**Comment by jonathan6661** [comment]
## Test without proxy:

![without proxy](https://user-images.githubusercontent.com/37407314/93212798-5bab5700-f763-11ea-88d8-7b64302dac99.JPG)

![email without proxy](https://user-images.githubusercontent.com/37407314/93212845-6cf46380-f763-11ea-8678-0b305ff53798.JPG)

## Test with a working proxy:

![with working proxy](https://user-images.githubusercontent.com/37407314/93212994-9b723e80-f763-11ea-870d-b24713df2bbc.JPG)

![email with a working proxy](https://user-images.githubusercontent.com/37407314/93213630-69151100-f764-11ea-9353-9e6160147d9e.JPG)

## Test with a non-functional proxy:

![with non working proxy](https://user-images.githubusercontent.com/37407314/93212915-85647e00-f763-11ea-9091-e6e06b05ef59.JPG)

![email with non working proxy](https://user-images.githubusercontent.com/37407314/93212922-87c6d800-f763-11ea-9151-4521177b5704.JPG)

Now i will just update the code, and i will extend the timeout to 15 second.

As the code works, i will close this issue.
